# Hartmann Heat Pump - Sensor Components (Polish)
# Pompa Ciepła Hartmann - Komponenty Sensor

sensor:
  # Sensory systemowe
  - platform: uptime
    name: "Czas działania"
    update_interval: 60s
  
  - platform: wifi_signal
    name: "Sygnał WiFi"
    update_interval: 60s

  # Sensory temperatury pompy ciepła
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Temperatura zewnętrzna"
    id: ambient_temp
    register_type: holding
    address: 40191  # B3: Temperatura powietrza zewnętrznego
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Temperatura wody powrotu"
    id: inlet_temp
    register_type: holding
    address: 40189  # B1: Temperatura wody powrotnej
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Temperatura wody zasilania"
    id: outlet_temp
    register_type: holding
    address: 40190  # B2: Temperatura wody zasilającej
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Temperatura sprężania"
    id: discharge_temp
    register_type: holding
    address: 40192  # B4: Temperatura tłoczna sprężarki
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Temperatura ssania"
    id: suction_temp
    register_type: holding
    address: 40193  # B5: Temperatura ssąca sprężarki
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Temperatura CWU"
    id: hot_water_temp
    register_type: holding
    address: 40196  # B8: Temperatura ciepłej wody użytkowej
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Temperatura parownika"
    id: coil_temp
    register_type: holding
    address: 40197  # B9: Temperatura wymiennika parownika
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  # Sensory ciśnienia
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Ciśnienie sprężania"
    id: discharge_pressure
    register_type: holding
    address: 40194  # B6: Czujnik wysokiego ciśnienia
    unit_of_measurement: "bar"
    value_type: FP32
    accuracy_decimals: 1
    device_class: pressure
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Ciśnienie ssania"
    id: suction_pressure
    register_type: holding
    address: 40195  # B7: Czujnik niskiego ciśnienia
    unit_of_measurement: "bar"
    value_type: FP32
    accuracy_decimals: 1
    device_class: pressure
    state_class: measurement

  # Sensory wydajności i sterowania
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Wyjście wentylatora"
    id: fan_output
    register_type: holding
    address: 40198  # Y1: Procent wyjścia prędkości wentylatora
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Wyjście pompy"
    id: pump_output
    register_type: holding
    address: 40199  # Y3: Procent wyjścia PWM pompy
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Prędkość sprężarki"
    id: compressor_speed
    register_type: holding
    address: 40206  # Rzeczywista prędkość sprężarki
    unit_of_measurement: "obr/s"
    value_type: FP32
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Otwarcie zaworu EEV"
    id: eev_opening
    register_type: holding
    address: 40208  # Otwarcie elektronicznego zaworu rozprężnego
    unit_of_measurement: "%"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Przegrzanie ssania"
    id: suction_superheat
    register_type: holding
    address: 40212  # Przegrzanie gazu ssącego
    unit_of_measurement: "K"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  # Dodatkowe sensory wydajności
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Prędkość wentylatora DC 1"
    id: dc_fan1_speed
    register_type: holding
    address: 40201  # Rzeczywista prędkość wentylatora DC 1
    unit_of_measurement: "obr/min"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Prędkość wentylatora DC 2"
    id: dc_fan2_speed
    register_type: holding
    address: 40203  # Rzeczywista prędkość wentylatora DC 2
    unit_of_measurement: "obr/min"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Wymagana wydajność"
    id: required_capacity
    register_type: holding
    address: 40204  # Wymagana wydajność sprężarki
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Aktualna wydajność"
    id: actual_capacity
    register_type: holding
    address: 40205  # Aktualna wydajność sprężarki
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement