# Hartmann Heat Pump - Binary Sensor Components (English)

binary_sensor:
  - platform: status
    name: "Connection Status"
    
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Flow Switch"
    id: flow_switch
    register_type: discrete_input
    address: 10002  # Flow switch status
    device_class: problem
    
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Circulation Pump Status"
    id: pump_status
    register_type: discrete_input
    address: 10179  # Circulation pump operation status
    device_class: running
    
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Compressor Status"
    id: compressor_status
    register_type: discrete_input
    address: 10180  # Compressor operation status
    device_class: running

  # Critical alarms - English
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Alarm: High Pressure"
    id: alarm_high_pressure
    register_type: discrete_input
    address: 10014  # AL001: High pressure
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Alarm: Low Pressure"
    id: alarm_low_pressure
    register_type: discrete_input
    address: 10015  # AL002: Low pressure
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Alarm: Inlet Probe Error"
    id: alarm_inlet_probe
    register_type: discrete_input
    address: 10016  # AL003: Inlet probe error
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Alarm: Outlet Probe Error"
    id: alarm_outlet_probe
    register_type: discrete_input
    address: 10017  # AL004: Outlet probe error
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Alarm: Ambient Probe Error"
    id: alarm_ambient_probe
    register_type: discrete_input
    address: 10018  # AL005: Ambient probe error
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Alarm: Flow Switch"
    id: alarm_flow_switch
    register_type: discrete_input
    address: 10020  # AL007: Water flow switch alarm
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Alarm: Phase Sequence"
    id: alarm_phase_sequence
    register_type: discrete_input
    address: 10021  # AL008: Phase sequence protection
    device_class: problem