# Hartmann Heat Pump - Sensor Components (English)
# Pompa Ciepła Hartmann - Sensor Components

sensor:
  # System sensors
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
  
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  # Heat pump temperature sensors
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Ambient Temperature"
    id: ambient_temp
    register_type: holding
    address: 40191  # B3: External air temperature
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Inlet Water Temperature"
    id: inlet_temp
    register_type: holding
    address: 40189  # B1: Return water temperature
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Outlet Water Temperature"
    id: outlet_temp
    register_type: holding
    address: 40190  # B2: Supply water temperature
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Discharge Gas Temperature"
    id: discharge_temp
    register_type: holding
    address: 40192  # B4: Compressor discharge temperature
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Suction Gas Temperature"
    id: suction_temp
    register_type: holding
    address: 40193  # B5: Compressor suction temperature
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hot Water Temperature"
    id: hot_water_temp
    register_type: holding
    address: 40196  # B8: Domestic hot water temperature
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Coil Temperature"
    id: coil_temp
    register_type: holding
    address: 40197  # B9: Evaporator coil temperature
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  # Pressure sensors
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Discharge Pressure"
    id: discharge_pressure
    register_type: holding
    address: 40194  # B6: High pressure sensor
    unit_of_measurement: "bar"
    value_type: FP32
    accuracy_decimals: 1
    device_class: pressure
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Suction Pressure"
    id: suction_pressure
    register_type: holding
    address: 40195  # B7: Low pressure sensor
    unit_of_measurement: "bar"
    value_type: FP32
    accuracy_decimals: 1
    device_class: pressure
    state_class: measurement

  # Performance and control sensors
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Fan Output"
    id: fan_output
    register_type: holding
    address: 40198  # Y1: Fan speed output percentage
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Pump Output"
    id: pump_output
    register_type: holding
    address: 40199  # Y3: Pump PWM output percentage
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Compressor Speed"
    id: compressor_speed
    register_type: holding
    address: 40206  # Actual compressor speed
    unit_of_measurement: "rps"
    value_type: FP32
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "EEV Opening"
    id: eev_opening
    register_type: holding
    address: 40208  # Electronic expansion valve opening
    unit_of_measurement: "%"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Suction Superheat"
    id: suction_superheat
    register_type: holding
    address: 40212  # Suction gas superheat
    unit_of_measurement: "K"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  # Additional performance sensors
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "DC Fan 1 Speed"
    id: dc_fan1_speed
    register_type: holding
    address: 40201  # DC Fan 1 actual speed
    unit_of_measurement: "rpm"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "DC Fan 2 Speed"
    id: dc_fan2_speed
    register_type: holding
    address: 40203  # DC Fan 2 actual speed
    unit_of_measurement: "rpm"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Required Capacity"
    id: required_capacity
    register_type: holding
    address: 40204  # Compressor required capacity
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Actual Capacity"
    id: actual_capacity
    register_type: holding
    address: 40205  # Compressor actual capacity
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement