# Hartmann Heat Pump - Unified Sensor Components
# Pompa Ciepła Hartmann - Ujednolicone Komponenty Sensor

sensor:
  # System sensors
  - platform: uptime
    name: "${uptime_name}"
    update_interval: 60s
  
  - platform: wifi_signal
    name: "${wifi_signal_name}"
    update_interval: 60s

  # Heat pump temperature sensors
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${ambient_temp_name}"
    id: ambient_temp
    register_type: holding
    address: 190  # B3: External air temperature (40191-40001=190)
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${inlet_temp_name}"
    id: inlet_temp
    register_type: holding
    address: 188  # B1: Return water temperature (40189-40001=188)
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${outlet_temp_name}"
    id: outlet_temp
    register_type: holding
    address: 189  # B2: Supply water temperature (40190-40001=189)
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${discharge_temp_name}"
    id: discharge_temp
    register_type: holding
    address: 191  # B4: Compressor discharge temperature (40192-40001=191)
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${suction_temp_name}"
    id: suction_temp
    register_type: holding
    address: 192  # B5: Compressor suction temperature (40193-40001=192)
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${hot_water_temp_name}"
    id: hot_water_temp
    register_type: holding
    address: 195  # B8: Domestic hot water temperature (40196-40001=195)
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${coil_temp_name}"
    id: coil_temp
    register_type: holding
    address: 196  # B9: Evaporator coil temperature (40197-40001=196)
    unit_of_measurement: "°C"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  # Pressure sensors
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${discharge_pressure_name}"
    id: discharge_pressure
    register_type: holding
    address: 193  # B6: High pressure sensor (40194-40001=193)
    unit_of_measurement: "bar"
    value_type: FP32
    accuracy_decimals: 1
    device_class: pressure
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${suction_pressure_name}"
    id: suction_pressure
    register_type: holding
    address: 194  # B7: Low pressure sensor (40195-40001=194)
    unit_of_measurement: "bar"
    value_type: FP32
    accuracy_decimals: 1
    device_class: pressure
    state_class: measurement

  # Performance and control sensors
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${fan_output_name}"
    id: fan_output
    register_type: holding
    address: 197  # Y1: Fan speed output percentage (40198-40001=197)
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${pump_output_name}"
    id: pump_output
    register_type: holding
    address: 198  # Y3: Pump PWM output percentage (40199-40001=198)
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${compressor_speed_name}"
    id: compressor_speed
    register_type: holding
    address: 205  # Actual compressor speed (40206-40001=205)
    unit_of_measurement: "rps"
    value_type: FP32
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${eev_opening_name}"
    id: eev_opening
    register_type: holding
    address: 207  # Electronic expansion valve opening (40208-40001=207)
    unit_of_measurement: "%"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${suction_superheat_name}"
    id: suction_superheat
    register_type: holding
    address: 211  # Suction gas superheat (40212-40001=211)
    unit_of_measurement: "K"
    value_type: FP32
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

  # Additional performance sensors
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${dc_fan1_speed_name}"
    id: dc_fan1_speed
    register_type: holding
    address: 200  # DC Fan 1 actual speed (40201-40001=200)
    unit_of_measurement: "rpm"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${dc_fan2_speed_name}"
    id: dc_fan2_speed
    register_type: holding
    address: 202  # DC Fan 2 actual speed (40203-40001=202)
    unit_of_measurement: "rpm"
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${required_capacity_name}"
    id: required_capacity
    register_type: holding
    address: 203  # Compressor required capacity (40204-40001=203)
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${actual_capacity_name}"
    id: actual_capacity
    register_type: holding
    address: 204  # Compressor actual capacity (40205-40001=204)
    unit_of_measurement: "%"
    value_type: FP32
    accuracy_decimals: 1
    state_class: measurement